global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "nodeapi"
    static_configs:
      - targets: ["api:5000"]   # if your Node app exposes /metrics

  - job_name: "javaapi"
    static_configs:
      - targets: ["webapi:9000"]  # if Java app exposes /actuator/prometheus

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb-exporter:9216"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql-exporter:9104"]
